apiVersion: v1
data:
    token: ENC[AES256_GCM,data:JdJHoqjLmkyc3E4zKgo5rOyDKGu2+uHK6xqo8dNYqVTee7kUzSI2N/cFIyuVvyuYPO83IjF2rL9Os8HHDG/AtA==,iv:uqPY0xd3TxvcvNLAnKMemrqjuS+sJc/Mf2tjsLfeZ+g=,tag:WuU7p00eUBAqHD8An1u00g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot-secret
    namespace: kbot-demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-8/locations/global/keyRings/sops-flux/cryptoKeys/sops-flux-key
          created_at: "2023-07-20T03:24:06Z"
          enc: CiQASPUePOnAW9V05cgVGFHI9xpK+s9OirtOt1KOoBMninVPJRsSSQA+o/wp5mr1a/H+EJ9Jn0NjrTc5LUUGQS9qrjPkO71h608crXtOa6qAvbkFtGicG0l5eiFMCfaXZW9U2pF53iWxa5fOIApZ7rg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-20T03:24:07Z"
    mac: ENC[AES256_GCM,data:78xYs7Sygc5glMPlWAL4oGjkwm+ZITWX3VIONu/9YW5NWuYx/Luf4r30ZB+NXSF0WlUlG74x5rFpbylQIKbtPF5AnJFu7RjRkNNbPHisEEE5z+/CrcfFuZ+SPVaS/dh9TyYJ3pNMnBW1rvatXBx3STSjmnIoX2bPtUTVdiTf5QE=,iv:VAmefvJTQP/bLvf3o/9+RW1WWoCo6X9W0BrrdjEP+EY=,tag:3TNmS3jtjIzc2jy6yfnZpA==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.7.3
