apiVersion: v1
data:
    token: ENC[AES256_GCM,data:IJ2I2q53thNkw8Rhj0W7n/2pLS2PKLL6cbMWdDHeZjyZR3xmY0CHM8A5zOC2J+H8bGHqiKLTIL9TBhyBzS4XxQ==,iv:ouSYPQXy+sC4DfykyTOZzLEFBtn+D3PKN8qMBx01nAs=,tag:nLz/egk4rrMkAMYCYoEXqw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot-secret
    namespace: kbot-demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-8/locations/global/keyRings/sops-flux/cryptoKeys/sops-flux-key
          created_at: "2023-07-22T01:52:54Z"
          enc: CiQASPUePMLdySGaj9biluTpmEjhbmvWKPOStQBLGFCQVbp/bL0SSQDf2I+EDks1niPZgIgOiY4OEzFgjefl1Wop4TqaWN+cUc9CDCWZ1CRKo5l/Fj7m6z2HO/Z3djNdc9ooLt6gw0k4WzeGK348KZo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-22T01:52:54Z"
    mac: ENC[AES256_GCM,data:MHxzFJhqi9Mse/V5yhSGdp/FS9uTCUYH9A+KgmiGdjZs6Gdn/aTMavQN+t44x7BggxeKQOyctmLXYU0fDDy68wKJ+qbtCJui9Lr+AajadCCn3MniK/CJ3bsQrnuvl2AltpO9iLYcwrKBWXB7AFIHskbHvQkAHQynA7dUaDwBtcI=,iv:/HpVW6rypgDQWyo77PgsDrnm+drrMEGG+RgrO/jVywg=,tag:79ervupBIHct/DCi3cv/vQ==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.7.3
