apiVersion: v1
data:
    token: ENC[AES256_GCM,data:D+vJREZwSaJ71TUeLEmAjqcX6hSaI3YKBFu/q2uKticbRULFEOMK3Uin9BcySek12xfvhbRhaPfz9S054gp1Wg==,iv:3gpV8D4GQeK8zDXmDHadmGBk5AkIEgmgZjzKMN8H3yg=,tag:YnVAV2smbZgRPfVvm6QY9g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot-secret
    namespace: kbot-demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-8/locations/global/keyRings/sops-flux/cryptoKeys/sops-flux-key
          created_at: "2023-07-22T15:41:48Z"
          enc: CiQASPUePL4RYOy99AJB5VteV7vdo8FnytQQAPAErCXkFz8WjFYSSQDQZMJmyl9IHjrWFsODlpUzdIcQZ0dAEaG2S7bfF2kEGKfq5wjBdAf67u4eKPkyiKTwDR44jvKJfzCeVvuGHgZh30sAZpvIVuY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-22T15:41:49Z"
    mac: ENC[AES256_GCM,data:64YNhtxoalBMU+MJ7ayoJQRwZYyIzWiplezqXsrFwms5LiY5cK3Q2cqPBXznok+VM5AIAPVqeNnU7vHZrR+6zh8BjuvPLKXUMFKP4zD813qG/HJKEVS6Xdu3+H3qNxXUUtApPNJ6gDK1o84xxHdAiyY24Q+JIa+5SUIoDyi5ZcA=,iv:+zxt0QVYdfeOnyN1zUxq8UoaThkKJO3nS+SvBszJ1m0=,tag:IIEDJg/464ecFiAVkZcPiA==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.7.3
